### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by gigawatts** [ripper121/OdroidGoOSMGPSOffline#3]
Do you have a fw file available that includes your most recent changes, such as disabling the speaker?

I am having trouble compiling the source myself. It compiles without errors in the Arduino IDE, but when uploaded to my Go, I just get a blank screen and no output on serial console. Are some extra undocumented steps/settings required to allow your app to work?

I know my Arduino IDE is setup correctly, as the [hello world](https://wiki.odroid.com/odroid_go/arduino/02_hello_world) example code compiles and runs just fine on my Go.

**Comment by gigawatts** [comment]
Update: I was finally able to get the code in this master branch to compile and build a new .fw file that works properly, but it would be nice to see an official release here hosting it for others.

**Comment by ripper121** [comment]
You could upload it to a 1 Click hoster and share the link here, then i will update the Github.
If you changed the code to get it running, please describe how to do it.
Im at the moment busy with other stuff.

**Comment by gigawatts** [comment]
@ripper121 
No source code modified, this is built straight from your master branch, I just updated my local copy of the ODROID-GO arduino library to the latest version and re-built the mkfw tool, and it worked fine this time around, I dont know why it didnt work last year when I tried to build it.

Here is my compiled and packed .fw file from your last commit, 2019-04-23  [OSM_GPS_20190423.zip](https://github.com/ripper121/OdroidGoOSMGPSOffline/files/6689946/OSM_GPS_20190423.zip)

**Comment by ripper121** [comment]
I added your release to the release list
